language: node_js
sudo: false
node_js:
- 8.9.4
install:
- npm install
script:
- npm run document
env:
  global:
    secure: xkh0tV8e2WXjNvBcwzaU1B6SHz5FZvVG0uDI6vmOOEC2kOmW2LQ5pkhUfywQGDhh44/2xGRPip/qbjUT8dglkCfSRV00pztkj14oF9EbGr38QUo77sdszPk/msw/zZD1bisteQ0Fs7XXz0+7IwH1BfwEEJv94fB99IERge5wLwlq3MbhDvnFtaowcp79UrqPcZKb2kE74hrXLnwSjIhmaAa+23eMz+W73uo82KnurpNmyEBkaQGjc4AZmddgV5XpEj6nle1Pd1nlkZA+noCZgOeJ48PSFi1gcaD77DLRoS8K8WrdLCsECjnIWhKqhaHmjPcMuc9eogv5+m1qOVamwfzmpdIsZrNj3qNnCFGa1lIjrA0wpd/szeb/k5bHmN0R0gxvDwtiL5PhdFes2Jk6QsRNBYOLVe4PSvtXLh91/R917Q9JtQPOTDSNgzwphxPUE3KOlsNQ46LL7W4tbJ+sbtZV3FlIlxJt5J/z9I8P3wVjbCq64Qrfl4ra7QRDidxrhULvFEIZAZ0J7lGi4K0Q/lKADMJvsamHGgYsPiFeFOf+p4hyp66/z3CDT0bnofLAiVu6J41v3iFD3vLNnaYVbVimtcjpPUVD3LXLKwjKv0BsMaPPfvyXK/azj0K8RtzSXW6cKfcQOmuNEnTtn0CVyjNLNAUewO4DLFJaqSORk5s=
